-- Create database
drop database godatabase;
CREATE DATABASE godatabase;
-- Ensure the database is on use
use godatabase;

CREATE TABLE Users (
    User_Key INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    USERNAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255),
    PASSWORD VARCHAR(255) NOT NULL
);

INSERT INTO Users (username, password) values ("UserA", "123456"), ("Userb", "123456");

CREATE TABLE D1_Stage_Saldos_Cartera (
    Id_Solicitud INT,
    Id_Credito INT,
    Id_Persona INT,
    Referencia VARCHAR(50) NULL,
    Afiliado VARCHAR(50) NULL,
    Nombre VARCHAR(100) NULL,
    Monto DECIMAL(10,2) NULL,
    Comision DECIMAL(10,2) NULL,
    Intereses_Totales DECIMAL(10,2) NULL,
    Monto_Total DECIMAL(10,2) NULL,
    Pagos INT NULL,
    Amort_Pagadas INT NULL,
    Capital_Pagado DECIMAL(10,2) NULL,
    Interes_Pagado DECIMAL(10,2) NULL,
    IVA_Int_Pagado DECIMAL(10,2) NULL,
    Cargo_PTardio_Pagado DECIMAL(10,2) NULL,
    Moratorio_Pagado DECIMAL(10,2) NULL,
    Pago_en_Exceso DECIMAL(10,2) NULL,
    Comision_Pagada DECIMAL(10,2) NULL,
    Total_Pagado DECIMAL(10,2) NULL,
    Ajustes_Capital DECIMAL(10,2) NULL,
    Saldo_Capital DECIMAL(10,2) NULL,
    Saldo_Interes DECIMAL(10,2) NULL,
    Saldo_IVA_Int DECIMAL(10,2) NULL,
    Saldo_Cargo_PTardio DECIMAL(10,2) NULL,
    Saldo_Moratorios DECIMAL(10,2) NULL,
    Saldo_Pago_Exceso DECIMAL(10,2) NULL,
    Saldo_Comision DECIMAL(10,2) NULL,
    Saldo_Total DECIMAL(10,2) NULL,
    Importe_de_Pago DECIMAL(10,2) NULL,
    Id_Convenio DECIMAL(10,2) NULL,
    Dependencia VARCHAR(100) NULL,
    Primer_Pago_Teorico TEXT NULL,
    Ultimo_Pago TEXT NULL,
    Tipo_Financiamiento VARCHAR(50) NULL,
    Capital_Vigente DECIMAL(10,2) NULL,
    Capital_Vencido DECIMAL(10,2) NULL,
    Intereses_Vencidos DECIMAL(10,2) NULL,
    Vencido DECIMAL(10,2) NULL,
    Sdo_Insoluto DECIMAL(10,2) NULL,
    Sdo_Total_c_ListasCobro DECIMAL(10,2) NULL,
    Sdo_Vencido_c_ListCobro DECIMAL(10,2) NULL,
    Estatus_Cartera VARCHAR(50) NULL,
    Estatus VARCHAR(20) NULL,
    Sucursal VARCHAR(100) NULL,
    Fecha_Desembolso TEXT NULL,
    Frecuencia VARCHAR(20) NULL,
    Primer_Pago_Real TEXT NULL,
    Ultimo_Pago_c_ListaCobro TEXT NULL,
    Ultimo_Pago_Aplicado TEXT NULL,
    Dias_Ultimo_Pago INT NULL,
    Dias_Atraso INT NULL,
    Cuotas_Atraso INT NULL,
    Periodos_Atraso INT NULL,
    Pago DECIMAL(10,2) NULL,
    Monto_Ultimo_Pago DECIMAL(10,2) NULL,
    Tasa_Int_Anual DECIMAL(10,2) NULL,
    Gestor VARCHAR(100) NULL,
    Motivo VARCHAR(100) NULL,
    Banco VARCHAR(100) NULL,
    Estado VARCHAR(100) NULL,
    Ciudad VARCHAR(100) NULL,
    Com_Vigente DECIMAL(10,2) NULL,
    Com_Vencida DECIMAL(10,2) NULL,
    Clabe VARCHAR(50) NULL,
    Sig_Pago TEXT NULL,
    Monto_Sig_Pago DECIMAL(10,2) NULL,
    vFondeador VARCHAR(100) NULL,
    Valida_Domi VARCHAR(100) NULL,
    vAfiliateIdO VARCHAR(100) NULL,
    vAfiliateO VARCHAR(100) NULL,
    Saldo_Retencion_Adm DECIMAL(10,2) NULL,
    RFC VARCHAR(20) NULL,
    vMotiveExt VARCHAR(100) NULL,
    iPeriodsExt INT NULL,
    vCommentExt VARCHAR(255) NULL,
    nRetencion DECIMAL(10,2) NULL,
    nJoPay DECIMAL(10,2) NULL,
    iMaxDays INT NULL,
    vMaxDate TEXT NULL,
    nLiquidate DECIMAL(10,2) NULL,
    nLiqPrin DECIMAL(10,2) NULL,
    nLiqInt DECIMAL(10,2) NULL,
    nLiqMor DECIMAL(10,2) NULL,
    nLiqCha DECIMAL(10,2) NULL,
    nLiqPrinTran DECIMAL(10,2) NULL,
    nLiqIntTran DECIMAL(10,2) NULL,
    nLiqMorTran DECIMAL(10,2) NULL,
    nLiqChaTran DECIMAL(10,2) NULL,
    nLiqRetTran DECIMAL(10,2) NULL,
    vScoreBuro VARCHAR(100) NULL,
    vCollectStatus VARCHAR(100) NULL,
    nCAT DECIMAL(10,2) NULL,
    vOpTable VARCHAR(50) NULL
);

CREATE TABLE D1_Saldos_Cartera (
    D1_Key int auto_increment primary key not null,
    Id_Solicitud INT,
    Id_Credito INT,
    Id_Persona INT,
    Referencia VARCHAR(50) NULL,
    Afiliado VARCHAR(50) NULL,
    Nombre VARCHAR(100) NULL,
    Monto DECIMAL(10,2) NULL,
    Comision DECIMAL(10,2) NULL,
    Intereses_Totales DECIMAL(10,2) NULL,
    Monto_Total DECIMAL(10,2) NULL,
    Pagos INT NULL,
    Amort_Pagadas INT NULL,
    Capital_Pagado DECIMAL(10,2) NULL,
    Interes_Pagado DECIMAL(10,2) NULL,
    IVA_Int_Pagado DECIMAL(10,2) NULL,
    Cargo_PTardio_Pagado DECIMAL(10,2) NULL,
    Moratorio_Pagado DECIMAL(10,2) NULL,
    Pago_en_Exceso DECIMAL(10,2) NULL,
    Comision_Pagada DECIMAL(10,2) NULL,
    Total_Pagado DECIMAL(10,2) NULL,
    Ajustes_Capital DECIMAL(10,2) NULL,
    Saldo_Capital DECIMAL(10,2) NULL,
    Saldo_Interes DECIMAL(10,2) NULL,
    Saldo_IVA_Int DECIMAL(10,2) NULL,
    Saldo_Cargo_PTardio DECIMAL(10,2) NULL,
    Saldo_Moratorios DECIMAL(10,2) NULL,
    Saldo_Pago_Exceso DECIMAL(10,2) NULL,
    Saldo_Comision DECIMAL(10,2) NULL,
    Saldo_Total DECIMAL(10,2) NULL,
    Importe_de_Pago DECIMAL(10,2) NULL,
    Id_Convenio DECIMAL(10,2) NULL,
    Dependencia VARCHAR(100) NULL,
    Primer_Pago_Teorico DATE NULL,
    Ultimo_Pago DATE NULL,
    Tipo_Financiamiento VARCHAR(50) NULL,
    Capital_Vigente DECIMAL(10,2) NULL,
    Capital_Vencido DECIMAL(10,2) NULL,
    Intereses_Vencidos DECIMAL(10,2) NULL,
    Vencido DECIMAL(10,2) NULL,
    Sdo_Insoluto DECIMAL(10,2) NULL,
    Sdo_Total_c_ListasCobro DECIMAL(10,2) NULL,
    Sdo_Vencido_c_ListCobro DECIMAL(10,2) NULL,
    Estatus_Cartera VARCHAR(50) NULL,
    Estatus VARCHAR(20) NULL,
    Sucursal VARCHAR(100) NULL,
    Fecha_Desembolso DATE NULL,
    Frecuencia VARCHAR(20) NULL,
    Primer_Pago_Real DATE NULL,
    Ultimo_Pago_c_ListaCobro DATE NULL,
    Ultimo_Pago_Aplicado DATE NULL,
    Dias_Ultimo_Pago INT NULL,
    Dias_Atraso INT NULL,
    Cuotas_Atraso INT NULL,
    Periodos_Atraso INT NULL,
    Pago DECIMAL(10,2) NULL,
    Monto_Ultimo_Pago DECIMAL(10,2) NULL,
    Tasa_Int_Anual DECIMAL(10,2) NULL,
    Gestor VARCHAR(100) NULL,
    Motivo VARCHAR(100) NULL,
    Banco VARCHAR(100) NULL,
    Estado VARCHAR(100) NULL,
    Ciudad VARCHAR(100) NULL,
    Com_Vigente DECIMAL(10,2) NULL,
    Com_Vencida DECIMAL(10,2) NULL,
    Clabe VARCHAR(50) NULL,
    Sig_Pago DATE NULL,
    Monto_Sig_Pago DECIMAL(10,2) NULL,
    vFondeador VARCHAR(100) NULL,
    Valida_Domi VARCHAR(100) NULL,
    vAfiliateIdO VARCHAR(100) NULL,
    vAfiliateO VARCHAR(100) NULL,
    Saldo_Retencion_Adm DECIMAL(10,2) NULL,
    RFC VARCHAR(20) NULL,
    vMotiveExt VARCHAR(100) NULL,
    iPeriodsExt INT NULL,
    vCommentExt VARCHAR(255) NULL,
    nRetencion DECIMAL(10,2) NULL,
    nJoPay DECIMAL(10,2) NULL,
    iMaxDays INT NULL,
    vMaxDate DATE NULL,
    nLiquidate DECIMAL(10,2) NULL,
    nLiqPrin DECIMAL(10,2) NULL,
    nLiqInt DECIMAL(10,2) NULL,
    nLiqMor DECIMAL(10,2) NULL,
    nLiqCha DECIMAL(10,2) NULL,
    nLiqPrinTran DECIMAL(10,2) NULL,
    nLiqIntTran DECIMAL(10,2) NULL,
    nLiqMorTran DECIMAL(10,2) NULL,
    nLiqChaTran DECIMAL(10,2) NULL,
    nLiqRetTran DECIMAL(10,2) NULL,
    vScoreBuro VARCHAR(100) NULL,
    vCollectStatus VARCHAR(100) NULL,
    nCAT DECIMAL(10,2) NULL,
    vOpTable VARCHAR(50) NULL,
    FechaGenerado DATETIME
);

CREATE TABLE D2_Stage_Saldos_Contables (
    Id_Credito INT not null,
    Referencia VARCHAR(50) not null,
    Nombre VARCHAR(100) NULL,
    Id_Sucursal INT NULL,
    Sucursal VARCHAR(100) NULL,
    Id_Convenio DECIMAL(10,2) NULL,
    Convenio VARCHAR(100) NULL,
    Financiamiento VARCHAR(50) NULL,
    Estatus_Inicial VARCHAR(10) NULL,
    Estatus_Final VARCHAR(10) NULL,
    Fecha_Apertura TEXT NULL,
    Fecha_Terminacion TEXT NULL,
    Importe DECIMAL(10,2) NULL,
    Dias_Atraso INT NULL,
    Cuotas_Atrasadas INT NULL,
    Periodos_Atraso INT NULL,
    Pagos_Sostenidos INT NULL,
    Pago DECIMAL(10,2) NULL,
    Frecuencia VARCHAR(20) NULL,
    Fecha_Ultimo_Pago TEXT NULL,
    Importe_Ultimo_Pago DECIMAL(10,2) NULL,
    Saldo_Inicial_Capital DECIMAL(10,2) NULL,
    Otorgado DECIMAL(10,2) NULL,
    Pagos DECIMAL(10,2) NULL,
    Ajuste_Cargo_Capital DECIMAL(10,2) NULL,
    Ajuste_Abono_Capital DECIMAL(10,2) NULL,
    Saldo_Final_Capital DECIMAL(10,2) NULL,
    Calculo DECIMAL(10,2) NULL,
    Diferencia DECIMAL(10,2) NULL,
    Capital_Vigente DECIMAL(10,2) NULL,
    Capital_Vencido DECIMAL(10,2) NULL,
    Saldo_Inicial_Interes DECIMAL(10,2) NULL,
    Devengamiento DECIMAL(10,2) NULL,
    Pagos_Interes DECIMAL(10,2) NULL,
    Ajuste_Cargo_Interes DECIMAL(10,2) NULL,
    Ajuste_Abono_Interes DECIMAL(10,2) NULL,
    Interes_No_Devengado DECIMAL(10,2) NULL,
    Saldo_Final_Interes DECIMAL(10,2) NULL,
    Calculo_Interes DECIMAL(10,2) NULL,
    Diferencia_Interes DECIMAL(10,2) NULL,
    Interes_Devengado DECIMAL(10,2) NULL,
    IVA_Interes_Devengado DECIMAL(10,2) NULL,
    Interes_No_DevengadoB DECIMAL(10,2) NULL,
    Fecha_Cartera_Vencida TEXT NULL,
    Saldo_Contable DECIMAL(10,2) NULL,
    Saldo_Insoluto DECIMAL(10,2) NULL,
    Porc_Provision DECIMAL(10,2) NULL,
    Reserva DECIMAL(10,2) NULL,
    nCAT DECIMAL(10,2) NULL,
    vOpTable VARCHAR(50) NULL,
    Status VARCHAR(20) NULL
);

CREATE TABLE D2_Saldos_Contables (
	D2_Key int auto_increment primary key not null,
    Id_Credito INT not null,
    Referencia VARCHAR(50) not null,
    Nombre VARCHAR(100) NULL,
    Id_Sucursal INT NULL,
    Sucursal VARCHAR(100) NULL,
    Id_Convenio DECIMAL(10,2) NULL,
    Convenio VARCHAR(100) NULL,
    Financiamiento VARCHAR(50) NULL,
    Estatus_Inicial VARCHAR(10) NULL,
    Estatus_Final VARCHAR(10) NULL,
    Fecha_Apertura DATE NULL,
    Fecha_Terminacion DATE NULL,
    Importe DECIMAL(10,2) NULL,
    Dias_Atraso INT NULL,
    Cuotas_Atrasadas INT NULL,
    Periodos_Atraso INT NULL,
    Pagos_Sostenidos INT NULL,
    Pago DECIMAL(10,2) NULL,
    Frecuencia VARCHAR(20) NULL,
    Fecha_Ultimo_Pago DATE NULL,
    Importe_Ultimo_Pago DECIMAL(10,2) NULL,
    Saldo_Inicial_Capital DECIMAL(10,2) NULL,
    Otorgado DECIMAL(10,2) NULL,
    Pagos DECIMAL(10,2) NULL,
    Ajuste_Cargo_Capital DECIMAL(10,2) NULL,
    Ajuste_Abono_Capital DECIMAL(10,2) NULL,
    Saldo_Final_Capital DECIMAL(10,2) NULL,
    Calculo DECIMAL(10,2) NULL,
    Diferencia DECIMAL(10,2) NULL,
    Capital_Vigente DECIMAL(10,2) NULL,
    Capital_Vencido DECIMAL(10,2) NULL,
    Saldo_Inicial_Interes DECIMAL(10,2) NULL,
    Devengamiento DECIMAL(10,2) NULL,
    Pagos_Interes DECIMAL(10,2) NULL,
    Ajuste_Cargo_Interes DECIMAL(10,2) NULL,
    Ajuste_Abono_Interes DECIMAL(10,2) NULL,
    Interes_No_Devengado DECIMAL(10,2) NULL,
    Saldo_Final_Interes DECIMAL(10,2) NULL,
    Calculo_Interes DECIMAL(10,2) NULL,
    Diferencia_Interes DECIMAL(10,2) NULL,
    Interes_Devengado DECIMAL(10,2) NULL,
    IVA_Interes_Devengado DECIMAL(10,2) NULL,
    Interes_No_DevengadoB DECIMAL(10,2) NULL,
    Fecha_Cartera_Vencida DATE NULL,
    Saldo_Contable DECIMAL(10,2) NULL,
    Saldo_Insoluto DECIMAL(10,2) NULL,
    Porc_Provision DECIMAL(10,2) NULL,
    Reserva DECIMAL(10,2) NULL,
    nCAT DECIMAL(10,2) NULL,
    vOpTable VARCHAR(50) NULL,
    Status VARCHAR(20) NULL,
    FechaGenerado DATETIME not null
);

CREATE TABLE D3_Stage_Aplicacion_Pagos (
    Id_Credito INT NULL,
    Id_Convenio INT NULL,
    Convenio VARCHAR(255) NULL,
    Referencia VARCHAR(255) NULL,
    Id_Pago INT NOT NULL,
    Nombre_Cliente VARCHAR(255) NULL,
    Financiamiento VARCHAR(255) NULL,
    Origen_de_Movimiento VARCHAR(255) NULL,
    Fecha_Pago TEXT NULL,
    Fecha_Aplicacion TEXT NULL,
    Fecha_Deposito TEXT NULL,
    Status VARCHAR(50) NULL,
    Pago DECIMAL(10, 2) NULL,
    Capital DECIMAL(10, 2) NULL,
    Interes DECIMAL(10, 2) NULL,
    IVA_Int DECIMAL(10, 2) NULL,
    Comision_Financiada DECIMAL(10, 2) NULL,
    IVA_Comision_Financ DECIMAL(10, 2) NULL,
    Moratorios DECIMAL(10, 2) NULL,
    IVA_Mora DECIMAL(10, 2) NULL,
    Pago_Tardio DECIMAL(10, 2) NULL,
    IVA_PagoTardio DECIMAL(10, 2) NULL,
    Recuperacion DECIMAL(10, 2) NULL,
    IVA_Recup DECIMAL(10, 2) NULL,
    Com_Liquidacion DECIMAL(10, 2) NULL,
    IVA_Com_Liquidacion DECIMAL(10, 2) NULL,
    Retencion_X_Admon DECIMAL(10, 2) NULL,
    IVA_Retencion_X_Admon DECIMAL(10, 2) NULL,
    Pago_Exceso DECIMAL(10, 2) NULL,
    Gestor VARCHAR(255) NULL,
    Forma_de_pago VARCHAR(255) NULL,
    vMotive VARCHAR(255) NULL
);

CREATE TABLE D3_Aplicacion_Pagos (
	D3_Key int auto_increment primary key not null,
    Id_Credito INT NULL,
    Id_Convenio INT NULL,
    Convenio VARCHAR(255) NULL,
    Referencia VARCHAR(255) NULL,
    Id_Pago INT NOT NULL,
    Nombre_Cliente VARCHAR(255) NULL,
    Financiamiento VARCHAR(255) NULL,
    Origen_de_Movimiento VARCHAR(255) NULL,
    Fecha_Pago DATE NULL,
    Fecha_Aplicacion DATE NULL,
    Fecha_Deposito DATE NULL,
    Status VARCHAR(50) NULL,
    Pago DECIMAL(10, 2) NULL,
    Capital DECIMAL(10, 2) NULL,
    Interes DECIMAL(10, 2) NULL,
    IVA_Int DECIMAL(10, 2) NULL,
    Comision_Financiada DECIMAL(10, 2) NULL,
    IVA_Comision_Financ DECIMAL(10, 2) NULL,
    Moratorios DECIMAL(10, 2) NULL,
    IVA_Mora DECIMAL(10, 2) NULL,
    Pago_Tardio DECIMAL(10, 2) NULL,
    IVA_PagoTardio DECIMAL(10, 2) NULL,
    Recuperacion DECIMAL(10, 2) NULL,
    IVA_Recup DECIMAL(10, 2) NULL,
    Com_Liquidacion DECIMAL(10, 2) NULL,
    IVA_Com_Liquidacion DECIMAL(10, 2) NULL,
    Retencion_X_Admon DECIMAL(10, 2) NULL,
    IVA_Retencion_X_Admon DECIMAL(10, 2) NULL,
    Pago_Exceso DECIMAL(10, 2) NULL,
    Gestor VARCHAR(255) NULL,
    Forma_de_pago VARCHAR(255) NULL,
    vMotive VARCHAR(255) NULL
);

CREATE TABLE D4_Stage_Otorgamiento_Creditos (
    Id_Credito INT PRIMARY KEY,
    Referencia VARCHAR(50) NULL,
    Nombre VARCHAR(100) NULL,
    Fecha_Apertura TEXT NULL,
    F_Cobro TEXT NULL,
    Id_Convenio INT NULL,
    Convenio VARCHAR(100) NULL,
    Id_Sucursal INT NULL,
    Sucursal VARCHAR(100) NULL,
    Capital DECIMAL(15, 2) NULL,
    Primer_Pago TEXT NULL,
    Comision DECIMAL(15, 2) NULL,
    IVA DECIMAL(15, 2) NULL,
    Cobertura DECIMAL(15, 2) NULL,
    IVA_Cobertura DECIMAL(15, 2) NULL,
    Disposicion DECIMAL(15, 2) NULL,
    Monto_Retenido DECIMAL(15, 2) NULL,
    Pago_de_Deuda DECIMAL(15, 2) NULL,
    Comision_Financiada DECIMAL(15, 2) NULL,
    IVA_Comision_Financiada DECIMAL(15, 2) NULL,
    Solicitud INT NULL,
    Vendedor INT NULL,
    Nombre_Vendedor VARCHAR(100) NULL,
    TipoVendedor VARCHAR(50) NULL,
    vSupervisorId INT NULL,
    vSupName VARCHAR(100) NULL,
    Producto VARCHAR(100) NULL,
    Descripcion_Tasa VARCHAR(100) NULL,
    Persona DECIMAL(15, 2) NULL,
    Plazo INT NULL,
    Id_Producto INT NULL,
    vCampaign VARCHAR(100) NULL,
    Tipo_de_Financiamiento VARCHAR(100) NULL,
    vFinancingTypeId INT NULL,
    vAliado VARCHAR(100) NULL
);

CREATE TABLE D4_Otorgamiento_Creditos (
	D4_Key int auto_increment primary key not null,
    Id_Credito INT,
    Referencia VARCHAR(50) NULL,
    Nombre VARCHAR(100) NULL,
    Fecha_Apertura DATE NULL,
    F_Cobro DATE NULL,
    Id_Convenio INT NULL,
    Convenio VARCHAR(100) NULL,
    Id_Sucursal INT NULL,
    Sucursal VARCHAR(100) NULL,
    Capital DECIMAL(15, 2) NULL,
    Primer_Pago DATE NULL,
    Comision DECIMAL(15, 2) NULL,
    IVA DECIMAL(15, 2) NULL,
    Cobertura DECIMAL(15, 2) NULL,
    IVA_Cobertura DECIMAL(15, 2) NULL,
    Disposicion DECIMAL(15, 2) NULL,
    Monto_Retenido DECIMAL(15, 2) NULL,
    Pago_de_Deuda DECIMAL(15, 2) NULL,
    Comision_Financiada DECIMAL(15, 2) NULL,
    IVA_Comision_Financiada DECIMAL(15, 2) NULL,
    Solicitud INT NULL,
    Vendedor INT NULL,
    Nombre_Vendedor VARCHAR(100) NULL,
    TipoVendedor VARCHAR(50) NULL,
    vSupervisorId INT NULL,
    vSupName VARCHAR(100) NULL,
    Producto VARCHAR(100) NULL,
    Descripcion_Tasa VARCHAR(100) NULL,
    Persona DECIMAL(15, 2) NULL,
    Plazo INT NULL,
    Id_Producto INT NULL,
    vCampaign VARCHAR(100) NULL,
    Tipo_de_Financiamiento VARCHAR(100) NULL,
    vFinancingTypeId INT NULL,
    vAliado VARCHAR(100) NULL
);

CREATE TABLE D5_Stage_Gestiones (
    Agencia_Registro VARCHAR(255),
    Causa_NoP_ago VARCHAR(255),
    Causa_No_Domiciliacion VARCHAR(255),
    Codigo_Accion INT,
    Codigo_Resultado INT,
    Comentarios TEXT,
    Contacto_Generado VARCHAR(255),
    Coordenadas VARCHAR(255),
    Credito INT,
    Estatus_Promesa VARCHAR(50),
    Fecha_Actividad TEXT,
    Fecha_Promesa TEXT,
    Monto_Promesa DECIMAL(10, 2),
    Origen VARCHAR(50),
    Producto VARCHAR(50),
    Resultado VARCHAR(50),
    Telefono VARCHAR(20),
    TipoPago VARCHAR(50),
    Usuario_Registro VARCHAR(50)
);

CREATE TABLE D5_Gestiones (
	D5_Key int auto_increment primary key not null,
    Agencia_Registro VARCHAR(255),
    Causa_No_Pago VARCHAR(255),
    Causa_No_Domiciliacion VARCHAR(255),
    Codigo_Accion INT,
    Codigo_Resultado INT,
    Comentarios TEXT,
    Contacto_Generado VARCHAR(255),
    Coordenadas VARCHAR(255),
    Credito INT,
    Estatus_Promesa VARCHAR(50),
    Fecha_Actividad DATETIME,
    Fecha_Promesa DATE,
    Monto_Promesa DECIMAL(10, 2),
    Origen VARCHAR(50),
    Producto VARCHAR(50),
    Resultado VARCHAR(50),
    Telefono VARCHAR(20),
    TipoPago VARCHAR(50),
    Usuario_Registro VARCHAR(50)
);

CREATE TABLE D6_Stage_Quebrantos (
    Operacion INT,
    Referencia INT,
    Nombre VARCHAR(255),
    Convenio VARCHAR(255),
    vFinancingtypeid VARCHAR(50),
    KVigente DECIMAL(10, 2),
    KVencido DECIMAL(10, 2),
    IntVencido DECIMAL(10, 2),
    IVAIntVencido DECIMAL(10, 2),
    IntVencidoCO DECIMAL(10, 2),
    IVAIntVencidoCO DECIMAL(10, 2),
    TotalQuebranto DECIMAL(10, 2),
    PagosRealizados DECIMAL(10, 2),
    SdoPendiente DECIMAL(10, 2),
    IntXDevengar DECIMAL(10, 2),
    SdoTotalXPagar DECIMAL(10, 2),
    FechaQuebranto VARCHAR(10),
    UltPagoTeorico VARCHAR(10),
    UltimoPago VARCHAR(10),
    UltPagoApl VARCHAR(10),
    Gestor VARCHAR(255),
    nCommission DECIMAL(10, 2),
    nCommTax DECIMAL(10, 2),
    vMotive VARCHAR(255)
);

CREATE TABLE D6_Quebrantos (
	D6_Key int auto_increment primary key not null,
    Operacion INT,
    Referencia INT,
    Nombre VARCHAR(255),
    Convenio VARCHAR(255),
    vFinancingtypeid VARCHAR(50),
    KVigente DECIMAL(10, 2),
    KVencido DECIMAL(10, 2),
    IntVencido DECIMAL(10, 2),
    IVAIntVencido DECIMAL(10, 2),
    IntVencidoCO DECIMAL(10, 2),
    IVAIntVencidoCO DECIMAL(10, 2),
    TotalQuebranto DECIMAL(10, 2),
    PagosRealizados DECIMAL(10, 2),
    SdoPendiente DECIMAL(10, 2),
    IntXDevengar DECIMAL(10, 2),
    SdoTotalXPagar DECIMAL(10, 2),
    FechaQuebranto VARCHAR(10),
    UltPagoTeorico VARCHAR(10),
    UltimoPago VARCHAR(10),
    UltPagoApl VARCHAR(10),
    Gestor VARCHAR(255),
    nCommission DECIMAL(10, 2),
    nCommTax DECIMAL(10, 2),
    vMotive VARCHAR(255),
    FechaGenerado DATETIME
);

CREATE TABLE D7_Stage_Juicios (
    Credito_MC INT,
    Decla VARCHAR(255),
    Descripcion_Cierre VARCHAR(255),
    Dias_Activo INT,
    Dias_Caducar INT,
    Estatus VARCHAR(50),
    Etapa_Procesal VARCHAR(50),
    Expediente INT,
    Fecha_Actualizacion TEXT,
    Fecha_Carga_Inicial TEXT,
    Fecha_Cierre TEXT,
    Fecha_Ultima_Act TEXT,
    Id_Juicio INT,
    Juzgado VARCHAR(255),
    Motivo_Cierre VARCHAR(255),
    Producto_MC VARCHAR(50),
    Tipo_Juicio VARCHAR(50),
    Validar_Cierre VARCHAR(50)
);

CREATE TABLE D7_Juicios (
	D7_Key int auto_increment primary key not null,
    Credito_MC INT,
    Decla VARCHAR(255),
    Descripcion_Cierre VARCHAR(255),
    Dias_Activo INT,
    Dias_Caducar INT,
    Estatus VARCHAR(50),
    Etapa_Procesal VARCHAR(50),
    Expediente INT,
    Fecha_Actualizacion DATETIME,
    Fecha_Carga_Inicial DATETIME,
    Fecha_Cierre DATETIME,
    Fecha_Ultima_Act DATETIME,
    Id_Juicio INT,
    Juzgado VARCHAR(255),
    Motivo_Cierre VARCHAR(255),
    Producto_MC VARCHAR(50),
    Tipo_Juicio VARCHAR(50),
    Validar_Cierre VARCHAR(50)
);

CREATE TABLE D8_Stage_Sistema (
    Agencia_Asignada_MC VARCHAR(255),
    Agencia_MC INT,
    Bandera_PP_Juicio INT,
    Codigo_MC INT,
    Credito_MC INT,
    Cuenta_Al_Corriente VARCHAR(3),
    Dias_en_la_instancia_actual INT,
    Dias_Para_Siguiente_Pago INT,
    Estatus_MC VARCHAR(50),
    Estrategia VARCHAR(255),
    Excepciones_MC VARCHAR(3),
    Fecha_de_Asignacion_CallCenter TEXT,
    Fecha_de_Asignacion_Visita TEXT,
    Fecha_De_Captura_de_Juicio TEXT,
    Fecha_de_Ultima_Visita TEXT,
    Fecha_Promesa_MC TEXT,
    Fecha_Ult_Gestion_MC TEXT,
    Importe_Pago_X2 DECIMAL(10,2),
    Importe_Pago_X3 DECIMAL(10,2),
    Importe_Pago_X4 DECIMAL(10,2),
    Importe_Pago_X6 DECIMAL(10,2),
    Monto_Promesa_MC DECIMAL(10,2),
    No_Gestiones INT,
    No_Visitas INT,
    Nombre_Agencia_MC VARCHAR(255),
    Nombre_Del_Deudor_MC VARCHAR(255),
    Nombre_Instancia_MC VARCHAR(255),
    Producto_MC VARCHAR(50),
    Quita_Exclusiva VARCHAR(3),
    Resultado_MC VARCHAR(255),
    Resultado_Visita_MC VARCHAR(255),
    Saldo_Menor DECIMAL(10,2),
    Semaforo_Gestion VARCHAR(50),
    Ult_Causa_No_Domiciliacion VARCHAR(255),
    Ult_Causa_No_Pago VARCHAR(255),
    Usuario_Asignado VARCHAR(255),
    Usuario_Asignado_Extrajudicial VARCHAR(255)
);

CREATE TABLE D8_Sistema (
	D8_Key int auto_increment primary key not null,
    Agencia_Asignada_MC VARCHAR(255),
    Agencia_MC INT,
    Bandera_PP_Juicio INT,
    Codigo_MC INT,
    Credito_MC INT,
    Cuenta_Al_Corriente VARCHAR(3),
    Dias_en_la_instancia_actual INT,
    Dias_Para_Siguiente_Pago INT,
    Estatus_MC VARCHAR(50),
    Estrategia VARCHAR(255),
    Excepciones_MC VARCHAR(3),
    Fecha_de_Asignacion_CallCenter DATETIME,
    Fecha_de_Asignacion_Visita DATETIME,
    Fecha_De_Captura_de_Juicio DATETIME,
    Fecha_de_Ultima_Visita DATETIME,
    Fecha_Promesa_MC DATETIME,
    Fecha_Ult_Gestion_MC DATETIME,
    Importe_Pago_X2 DECIMAL(10,2),
    Importe_Pago_X3 DECIMAL(10,2),
    Importe_Pago_X4 DECIMAL(10,2),
    Importe_Pago_X6 DECIMAL(10,2),
    Monto_Promesa_MC DECIMAL(10,2),
    No_Gestiones INT,
    No_Visitas INT,
    Nombre_Agencia_MC VARCHAR(255),
    Nombre_Del_Deudor_MC VARCHAR(255),
    Nombre_Instancia_MC VARCHAR(255),
    Producto_MC VARCHAR(50),
    Quita_Exclusiva VARCHAR(3),
    Resultado_MC VARCHAR(255),
    Resultado_Visita_MC VARCHAR(255),
    Saldo_Menor DECIMAL(10,2),
    Semaforo_Gestion VARCHAR(50),
    Ult_Causa_No_Domiciliacion VARCHAR(255),
    Ult_Causa_No_Pago VARCHAR(255),
    Usuario_Asignado VARCHAR(255),
    Usuario_Asignado_Extrajudicial VARCHAR(255)
);

CREATE TABLE D9_Stage_Catalogo_Gestores_Area(
    UsuarioMC VARCHAR(50) NULL,
    Area VARCHAR(50) NULL,
    Estatus Int NULL,
    Perfil VARCHAR(50) NULL
);

CREATE TABLE D9_Catalogo_Gestores_Area(
	D9_Key int auto_increment primary key not null,
    UsuarioMC VARCHAR(50) NULL,
    Area VARCHAR(50) NULL,
    Estatus Int NULL,
    Perfil VARCHAR(50) NULL
);

CREATE TABLE C1_Dependencia(
	C1_Key int auto_increment primary key not null,
    Dependencia VARCHAR(100) NULL,
    Abreviatura VARCHAR(100) NULL
);

CREATE TABLE C2_Financiamiento(
	C2_Key int auto_increment primary key not null,
    Tipo_Financiamiento VARCHAR(50) NULL,
    Financiamiento VARCHAR(50) NULL,
    Producto VARCHAR(50) NULL
);

CREATE TABLE C3_Motivo(
	C3_Key int auto_increment primary key not null,
    Motivo VARCHAR(100) NULL,
    BanderaPago VARCHAR(50) NULL,
    BanderaDependendia VARCHAR(50) NULL,
    Abreviatura VARCHAR(50) NULL
);

CREATE TABLE C4_Catalogo_Bancos(
	C4_Key int auto_increment primary key not null,
	Clabe VARCHAR(100) NULL,
	NombreCorto VARCHAR(100) NULL,
	RazonSocial VARCHAR(100) NULL
);

CREATE TABLE C5_Referencias (
	C5_Key int auto_increment primary key not null,
    Id_Persona INT NOT NULL,  -- Assuming ipersonid is an integer, adjust the type as needed
    Referencia1 VARCHAR(255),
    RELACION1 VARCHAR(255),
    vphonenumber1 VARCHAR(20),
    Referencia2 VARCHAR(255),
    RELACION2 VARCHAR(255),
    vphonenumber2 VARCHAR(20),
    Referencia3 VARCHAR(255),
    RELACION3 VARCHAR(255),
    vphonenumber3 VARCHAR(20),
    Referencia4 VARCHAR(255),
    RELACION4 VARCHAR(255),
    vphonenumber4 VARCHAR(20),
    Referencia5 VARCHAR(255),
    RELACION5 VARCHAR(255),
    vphonenumber5 VARCHAR(20),
    Referencia6 VARCHAR(255),
    RELACION6 VARCHAR(255),
    vphonenumber6 VARCHAR(20),
    Referencia7 VARCHAR(255),
    RELACION7 VARCHAR(255),
    vphonenumber7 VARCHAR(20),
    Referencia8 VARCHAR(255),
    RELACION8 VARCHAR(255),
    vphonenumber8 VARCHAR(20),
    Referencia9 VARCHAR(255),
    RELACION9 VARCHAR(255),
    vphonenumber9 VARCHAR(20),
    Referencia10 VARCHAR(255),
    RELACION10 VARCHAR(255),
    vphonenumber10 VARCHAR(20),
    Referencia11 VARCHAR(255),
    RELACION11 VARCHAR(255),
    vphonenumber11 VARCHAR(20),
    Referencia12 VARCHAR(255),
    RELACION12 VARCHAR(255),
    vphonenumber12 VARCHAR(20),
    Referencia13 VARCHAR(255),
    RELACION13 VARCHAR(255),
    vphonenumber13 VARCHAR(20),
    Referencia14 VARCHAR(255),
    RELACION14 VARCHAR(255),
    vphonenumber14 VARCHAR(20),
    Referencia15 VARCHAR(255),
    RELACION15 VARCHAR(255),
    vphonenumber15 VARCHAR(20),
    Referencia16 VARCHAR(255),
    RELACION16 VARCHAR(255),
    vphonenumber16 VARCHAR(20),
    Referencia17 VARCHAR(255),
    RELACION17 VARCHAR(255),
    vphonenumber17 VARCHAR(20),
    Referencia18 VARCHAR(255),
    RELACION18 VARCHAR(255),
    vphonenumber18 VARCHAR(20),
    Referencia19 VARCHAR(255),
    RELACION19 VARCHAR(255),
    vphonenumber19 VARCHAR(20),
    Referencia20 VARCHAR(255),
    RELACION20 VARCHAR(255),
    vphonenumber20 VARCHAR(20),
    Referencia21 VARCHAR(255),
    RELACION21 VARCHAR(255),
    vphonenumber21 VARCHAR(20),
    Referencia22 VARCHAR(255),
    RELACION22 VARCHAR(255),
    vphonenumber22 VARCHAR(20)
);

CREATE TABLE C6_Catalogo_Resultados_Avances(
	C6_Key int auto_increment primary key not null,
	Clave VARCHAR(50) NULL,
    Resultado VARCHAR(50) NULL
);

CREATE TABLE CI1_Pagos_Estrategia_Acumulados(
	CI1_Key int auto_increment primary key not null,
	IdPago INT NULL
);

CREATE TABLE CI2_Estatus_Domi(
	CI2_Key int auto_increment primary key not null,
	IdCredito INT NULL,
    Rechazo VARCHAR(50) NULL
);

CREATE TABLE CI3_Plazas(
	CI3_Key int auto_increment primary key not null,
    Id_Credito INT not null,
    Plaza VARCHAR(100)
);

CREATE TABLE B1_Demograficos(
	B1_Key int auto_increment primary key not null,
    Id_Persona INT NOT NULL,
    vName VARCHAR(120) NULL,
    vFirstName VARCHAR(30) NULL,
    vSecondName VARCHAR(30) NULL,
    vFLastName VARCHAR(30) NULL,
    vSLastName VARCHAR(30) NULL,
    vOpIdType VARCHAR(20) NULL,
    vIdNumber VARCHAR(20) NULL,
    vTreasuryId VARCHAR(20) NULL,
    vStateId VARCHAR(10) NULL,
    vLegalId VARCHAR(20) NULL,
    vOpSex VARCHAR(20) NULL,
    vOpNationality VARCHAR(20) NULL,
    vOpMaritalStatus VARCHAR(20) NULL,
    vOpMaritalRegime VARCHAR(20) NULL,
    vBirthDate VARCHAR(20) NULL,
    vEMail VARCHAR(50) NULL,
    iDependents INT NULL,
    vOpEducation VARCHAR(20) NULL,
    vSpFirstName VARCHAR(30) NULL,
    vSpSecondName VARCHAR(30) NULL,
    vSpFLastName VARCHAR(30) NULL,
    vSpSLastName VARCHAR(30) NULL,
    vMobile VARCHAR(20) NULL,
    vOpPropTypeAd VARCHAR(20) NULL,
    vStreetAd VARCHAR(50) NULL,
    vExtNumberAd VARCHAR(20) NULL,
    vIntNumberAd VARCHAR(20) NULL,
    vCornerAd VARCHAR(50) NULL,
    vCCornerAd VARCHAR(50) NULL,
    vNeighborhoodAd VARCHAR(50) NULL,
    vTownshipAd VARCHAR(50) NULL,
    vCountryIdAd VARCHAR(10) NULL,
    vCityAd VARCHAR(50) NULL,
    vStateIdAd VARCHAR(10) NULL,
    vZoneAd VARCHAR(50) NULL,
    iZipAd INT NULL,
    vPhoneNumberAd VARCHAR(20) NULL,
    iYearsAd INT NULL,
    iMonthsAd INT NULL,
    vCompanyJo VARCHAR(50) NULL,
    nPayJo DECIMAL(15, 2) NULL,
    vPhoneNumberJo VARCHAR(20) NULL,
    vExtensionNumberJo VARCHAR(10) NULL,
    vSectorIdJo VARCHAR(10) NULL,
    vSectorActivityIdJo VARCHAR(10) NULL,
    vBossJo VARCHAR(50) NULL,
    vPositionJo VARCHAR(50) NULL,
    iYearsJo INT NULL,
    iMonthsJo INT NULL,
    vOpEmployeeTypeJo VARCHAR(20) NULL,
    vStreetJo VARCHAR(50) NULL,
    vExtNumberJo VARCHAR(20) NULL,
    vIntNumberJo VARCHAR(20) NULL,
    vCornerJo VARCHAR(50) NULL,
    vCCornerJo VARCHAR(50) NULL,
    vNeighborhoodJo VARCHAR(50) NULL,
    vTownshipJo VARCHAR(50) NULL,
    vCountryIdJo VARCHAR(10) NULL,
    vCityJo VARCHAR(50) NULL,
    vStateIdJo VARCHAR(10) NULL,
    vZoneJo VARCHAR(50) NULL,
    iZipJo INT NULL,
    vOpTypeJo VARCHAR(20) NULL,
    vOpBusiness VARCHAR(20) NULL,
    vOpLocation VARCHAR(20) NULL,
    vOpOwnership VARCHAR(20) NULL,
    vOpRelationType1 VARCHAR(20) NULL,
    vFirstNameRe1 VARCHAR(30) NULL,
    vSecondNameRe1 VARCHAR(30) NULL,
    vFLastNameRe1 VARCHAR(30) NULL,
    vSLastNameRe1 VARCHAR(30) NULL,
    vPhoneNumberRe1 VARCHAR(20) NULL,
    iYearsRe1 INT NULL,
    iMonthsRe1 INT NULL,
    vStreetRe1 VARCHAR(50) NULL,
    vExtNumberRe1 VARCHAR(20) NULL,
    vIntNumberRe1 VARCHAR(20) NULL,
    vCornerRe1 VARCHAR(50) NULL,
    vCCornerRe1 VARCHAR(50) NULL,
    vNeighborhoodRe1 VARCHAR(50) NULL,
    vTownshipRe1 VARCHAR(50) NULL,
    vCityRe1 VARCHAR(50) NULL,
    vStateIdRe1 VARCHAR(10) NULL,
    vCountryIdRe1 VARCHAR(10) NULL,
    vZoneRe1 VARCHAR(50) NULL,
    iZipRe1 INT NULL,
    vOpRelationType2 VARCHAR(20) NULL,
    vFirstNameRe2 VARCHAR(30) NULL,
    vSecondNameRe2 VARCHAR(30) NULL,
    vFLastNameRe2 VARCHAR(30) NULL,
    vSLastNameRe2 VARCHAR(30) NULL,
    vPhoneNumberRe2 VARCHAR(20) NULL,
    iYearsRe2 INT NULL,
    iMonthsRe2 INT NULL,
    vStreetRe2 VARCHAR(50) NULL,
    vExtNumberRe2 VARCHAR(20) NULL,
    vIntNumberRe2 VARCHAR(20) NULL,
    vCornerRe2 VARCHAR(50) NULL,
    vCCornerRe2 VARCHAR(50) NULL,
    vNeighborhoodRe2 VARCHAR(50) NULL,
    vTownshipRe2 VARCHAR(50) NULL,
    vCityRe2 VARCHAR(50) NULL,
    vStateIdRe2 VARCHAR(10) NULL,
    vCountryIdRe2 VARCHAR(10) NULL,
    vZoneRe2 VARCHAR(50) NULL,
    iZipRe2 INT NULL,
    vOpRelationType3 VARCHAR(20) NULL,
    vFirstNameRe3 VARCHAR(30) NULL,
    vSecondNameRe3 VARCHAR(30) NULL,
    vFLastNameRe3 VARCHAR(30) NULL,
    vSLastNameRe3 VARCHAR(30) NULL,
    vPhoneNumberRe3 VARCHAR(20) NULL,
    iYearsRe3 INT NULL,
    iMonthsRe3 INT NULL,
    vStreetRe3 VARCHAR(50) NULL,
    vExtNumberRe3 VARCHAR(20) NULL,
    vIntNumberRe3 VARCHAR(20) NULL,
    vCCornerRe3 VARCHAR(50) NULL,
    vCornerRe3 VARCHAR(50) NULL,
    vNeighborhoodRe3 VARCHAR(50) NULL,
    vTownshipRe3 VARCHAR(50) NULL,
    vCityRe3 VARCHAR(50) NULL,
    vStateIdRe3 VARCHAR(10) NULL,
    vCountryIdRe3 VARCHAR(10) NULL,
    vZoneRe3 VARCHAR(50) NULL,
    iZipRe3 INT NULL,
    vOpRelationType4 VARCHAR(20) NULL,
    vFirstNameRe4 VARCHAR(30) NULL,
    vSecondNameRe4 VARCHAR(30) NULL,
    vFLastNameRe4 VARCHAR(30) NULL,
    vSLastNameRe4 VARCHAR(30) NULL,
    vPhoneNumberRe4 VARCHAR(20) NULL,
    iYearsRe4 INT NULL,
    iMonthsRe4 INT NULL,
    vStreetRe4 VARCHAR(50) NULL,
    vExtNumberRe4 VARCHAR(20) NULL,
    vIntNumberRe4 VARCHAR(20) NULL,
    vCornerRe4 VARCHAR(50) NULL,
    vCCornerRe4 VARCHAR(50) NULL,
    vNeighborhoodRe4 VARCHAR(50) NULL,
    vTownshipRe4 VARCHAR(50) NULL,
    vCityRe4 VARCHAR(50) NULL,
    vStateIdRe4 VARCHAR(10) NULL,
    vCountryIdRe4 VARCHAR(10) NULL,
    vZoneRe4 VARCHAR(50) NULL,
    iZipRe4 INT NULL,
    vOpCommType1 VARCHAR(20) NULL,
    vCompanyCom1 VARCHAR(50) NULL,
    vReferenceCom1 VARCHAR(20) NULL,
    nAmountCom1 DECIMAL(15, 2) NULL,
    nBalanceCom1 DECIMAL(15, 2) NULL,
    iYearsCom1 INT NULL,
    iMonthsCom1 INT NULL,
    vOpCommType2 VARCHAR(20) NULL,
    vCompanyCom2 VARCHAR(50) NULL,
    vReferenceCom2 VARCHAR(20) NULL,
    nAmountCom2 DECIMAL(15, 2) NULL,
    nBalanceCom2 DECIMAL(15, 2) NULL,
    iYearsCom2 INT NULL,
    iMonthsCom2 INT NULL,
    vOpCommType3 VARCHAR(20) NULL,
    vCompanyCom3 VARCHAR(50) NULL,
    vReferenceCom3 VARCHAR(20) NULL,
    nAmountCom3 DECIMAL(15, 2) NULL,
    nBalanceCom3 DECIMAL(15, 2) NULL,
    iYearsCom3 INT NULL,
    iMonthsCom3 INT NULL,
    vOpCommType4 VARCHAR(20) NULL,
    vCompanyCom4 VARCHAR(50) NULL,
    vReferenceCom4 VARCHAR(20) NULL,
    nAmountCom4 DECIMAL(15, 2) NULL,
    nBalanceCom4 DECIMAL(15, 2) NULL,
    iYearsCom4 INT NULL,
    iMonthsCom4 INT NULL,
    dtInsert DATETIME NULL,
    dtUpdate DATETIME NULL
);

CREATE TABLE R1_Quebrantos_Calculado(
	R1_Key int auto_increment primary key not null,
    Operacion INT,
    Referencia INT,
    Nombre VARCHAR(255),
    Convenio VARCHAR(255),
    vFinancingtypeid VARCHAR(50),
    KVigente DECIMAL(10, 2),
    KVencido DECIMAL(10, 2),
    IntVencido DECIMAL(10, 2),
    IVAIntVencido DECIMAL(10, 2),
    IntVencidoCO DECIMAL(10, 2),
    IVAIntVencidoCO DECIMAL(10, 2),
    TotalQuebranto DECIMAL(10, 2),
    PagosRealizados DECIMAL(10, 2),
    SdoPendiente DECIMAL(10, 2),
    IntXDevengar DECIMAL(10, 2),
    SdoTotalXPagar DECIMAL(10, 2),
    FechaQuebranto VARCHAR(10),
    UltPagoTeorico VARCHAR(10),
    UltimoPago VARCHAR(10),
    UltPagoApl VARCHAR(10),
    Gestor VARCHAR(255),
    nCommission DECIMAL(10, 2),
    nCommTax DECIMAL(10, 2),
    vMotive VARCHAR(255),
    TotalEstrategia DECIMAL(18, 2),
    SaldoReal DECIMAL(18, 2),
    CapitalQuebrantado DECIMAL(18, 2),
    Recuperacion DECIMAL(18, 2),
    Month INT,
    Year INT,
    QuebrantoContable DECIMAL(18, 2),
    Producto VARCHAR(255),
    Financiamiento VARCHAR(50),
    Valid INT,
    SaldoCapital DECIMAL(18, 2),
    Motivo DECIMAL(18, 2),
	FechaGenerado DATETIME
);

CREATE TABLE R2_BDops (
	R2_Key int auto_increment primary key not null,
    Id_Solicitud INT,
    Id_Credito INT,
    Id_Persona INT,
    Antiguedad_Cliente DATETIME,
    Capital_Total_Dispersado DECIMAL(10, 2),
    Capital_Total_Dispersado_Credito DECIMAL(10, 2),
    Pago_Total_Cliente DECIMAL(10, 2),
    Pago_Total_Credito DECIMAL(10, 2),
    PagadoVsDispersado DECIMAL(10, 2),
    Pago_Mes_Vigente DECIMAL(10, 2),
    Cuotas_Pagadas_Mes_Vigente INT,
    Rango_Pagado_Mes_Vigente VARCHAR(50),
    Pago_Mes_Anterior DECIMAL(10, 2),
    Cuotas_Pagadas_Mes_Anterior INT,
    Rango_Pagado_Mes_Anterior VARCHAR(50),
    Pago_30_Dias DECIMAL(10, 2),
    Cuotas_Pagadas_30_Dias INT,
    Rango_Pagado_30_Dias VARCHAR(50),
    Pago_15_Dias DECIMAL(10, 2),
    Cuotas_Pagadas_15_Dias INT,
    Rango_Pagado_15_Dias VARCHAR(50),
    Bandera VARCHAR(50),
    Score INT,
    Nombre VARCHAR(100),
    Monto DECIMAL(10, 2),
    Monto_Total DECIMAL(10, 2),
    Pagos INT,
    AmortPagadas INT,
    Avance DECIMAL(5, 2),
    Rango_Avance VARCHAR(50),
    Cuotas_Pag_Rango VARCHAR(50),
    vFondeador INT,
    Dependencia VARCHAR(100),
    UN_Dependencia VARCHAR(100),
    Tipo_Financiamiento VARCHAR(50),
    UN_Financiamiento VARCHAR(50),
    Sucursal VARCHAR(100),
    Nombre_Vendedor VARCHAR(100),
    Nombre_Supervisor VARCHAR(100),
    F_Desembolso DATETIME,
    Frecuencia VARCHAR(50),
    Tasa_Int_Anual DECIMAL(5, 2),
    Producto VARCHAR(100),
    Estatus VARCHAR(50),
    EstatusDef INT,
    Propenso_a_Castigo BOOLEAN,
    Mes_Quebranto INT,
    TotalCreditos INT,
    Creditos_Activo INT,
    Creditos_Castigado INT,
    Creditos_Cerrado INT,
    Etapa_Legal VARCHAR(100),
    Etapa_Legal_MC VARCHAR(100),
    Motivo VARCHAR(100),
    Bandera_Pago_No_Pago_Nómina VARCHAR(50),
    Bandera_Baja_Dependencia VARCHAR(50),
    Abreviatura VARCHAR(50),
    Estado VARCHAR(50),
    Ciudad VARCHAR(50),
    Plaza VARCHAR(50),
    Total_Pagado DECIMAL(10, 2),
    Saldo_Contable DECIMAL(10, 2),
    Saldo_Capital DECIMAL(10, 2),
    Saldo_Total DECIMAL(10, 2),
    Importe_de_Pago DECIMAL(10, 2),
    Vencido DECIMAL(10, 2),
    Vencido_Cliente DECIMAL(10, 2),
    SdoInsoluto DECIMAL(10, 2),
    Pago DECIMAL(10, 2),
    Saldo_Pagare DECIMAL(10, 2),
    Saldo_Q_Contable DECIMAL(10, 2),
    Saldo_Q_Capital DECIMAL(10, 2),
    Recuperación DECIMAL(10, 2),
    FechaQuebranto DATETIME,
    Fecha_Ingreso DATETIME,
    Primer_Pago_Teorico DATETIME,
    Primer_Pago_Real DATETIME,
    Ultimo_pago_c_ListaCobro DATETIME,
    Ultimo_pago_aplicado DATETIME,
    DiasUltimoPago INT,
    MontoUltimoPago DECIMAL(10, 2),
    DiasAtraso INT,
    Bkt_Actual VARCHAR(50),
    PeriodosAtraso INT,
    DiasAtraso_Inicial INT,
    Bkt_Inicial VARCHAR(50),
    Sig_Pago DATETIME,
    Monto_Sig_Pago DECIMAL(10, 2),
    vCommentExt VARCHAR(255),
    iPeriodsExt INT,
    vScoreBuro VARCHAR(50),
    vCollectStatus VARCHAR(50),
    Banco VARCHAR(50),
    Clabe VARCHAR(50),
    Clabe_Corta VARCHAR(50),
    Banco_Calculado VARCHAR(50),
    Estatus_Domi VARCHAR(50),
    Causa_de_No_Pago VARCHAR(100),
    Causa_No_Domiciliación VARCHAR(100),
    Historia_Gestiones TEXT,
    Historia_Llamadas TEXT,
    Historia_Visitas TEXT,
    Historia_Gestiones_Externos TEXT,
    Historia_RPC TEXT,
    Historia_PTP TEXT,
    Historia_PTP_Cumplida TEXT,
    Historia_PTP_Parcial TEXT,
    Historia_PTP_Rota TEXT,
    Gestiones INT,
    Llamadas INT,
    Visitas INT,
    Gestiones_Externos INT,
    RPC INT,
    PTP INT,
    PTP_Cumplida INT,
    PTP_Parcial_Vigente INT,
    PTP_Parcial_Vencida INT,
    PTP_Vigente INT,
    PTP_Rota INT,
    Telefono_1 VARCHAR(20),
    Telefono_2 VARCHAR(20),
    Domicilio VARCHAR(255),
    Entre_Calles VARCHAR(255),
    Colonia VARCHAR(100),
    Ciudad_Demograficos VARCHAR(100),
    Estado_Demograficos VARCHAR(50),
    Codigo_Postal VARCHAR(10),
    Bandera_PP_Juicio VARCHAR(50),
    Referencia VARCHAR(100),
    Tipo_de_Credito VARCHAR(50),
	FechaGenerado DATETIME
);